stages:
  - docu
  - deploy

docu:
  stage: docu
  tags:
    - shell
  script:
    - virtualenv _venv
    - source _venv/bin/activate
    - python -m pip install -e .
    - cd docs
    - export DISPLAY=:0
    - xvfb-run -a -s "-screen 0 1400x900x24 +extension RANDR" make html
    - rm -rf /srv/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - mkdir -p /srv/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - mv _build/html/* /srv/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - cd ..
    - pip uninstall -y pywisp
    - deactivate
    - rm -rf *
  only:
    - master

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - virtualenv _venv
    - source _venv/bin/activate
    - pip install -U twine
    - python -m pip install .
    - python -m build
    - twine upload dist/* --config-file /etc/pypirc
    - pip uninstall -y pywisp
    - rm -rf *
  only:
    - tags
