/** This file is autogenerated, do not edit */
#pragma once
#include <Eigen/Dense>
#include <cmath>
using Eigen::Matrix;
namespace LinOneMassOscillator {
    using State = OneMassOscillator::State;
    using Input = OneMassOscillator::Input;
    using Parameters = OneMassOscillator::Parameters;
    State step(State x, Input u, Parameters p) {
        auto y = x(0);
        auto dy = x(1);

        auto m = p(0);
        auto b = p(1);
        auto k = p(2);

        auto F = u;

        State dx;
        dx[0] = dy;
        dx[1] = (m == 0.0) ? 0 : 1/m * (u - b*dy - k*y);
        
        return dx;
    };
};
